name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    if: ${{ github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Add WASM target
      run: rustup target install wasm32-wasip1 
      
    - name: Build
      run: cargo build --verbose
        
  release:
    if: ${{ github.event_name != 'pull_request' }}
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v4
      
      - name: Add WASM target
        run: rustup target install wasm32-wasip1 
      
      - name: Install NuShell
        run: ./scripts/install_nushell.sh

      - name: Build Release
        run: cargo build --release
          
      - name: Publish Release
        run: ./scripts/release.nu
        env: 
          GH_TOKEN: ${{ github.token }}
